# general configuration
url: https://calciumargon.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: # "images/github_avatar_small.jpg"
  # author will appear under the avatar (optional)
  author: "Ray Tao"
  # tagline will appear under the title (optional)
  tagline: "<a href='http://jekyllrb.com'>Jekyll</a> I'm Taorui undergraduated student.I'm Taorui undergraduated student.I'm Taorui undergraduated student.I'm Taorui undergraduated student.I'm Taorui undergraduated student.I'm Taorui undergraduated student.\nI'm Taorui undergraduated student.I'm Taorui undergraduated student.I'm Taorui undergraduated student.I'm Taorui undergraduated student."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "compass"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
